exclude: ^(.travis.yml|.pre-commit-config.yaml|.bumpversion.cfg)$
fail_fast: true
repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 3ad5e9834d138bc7d9f5a2e7d6485bab5484d0e1  # frozen: v5.10.1
  hooks:
  - id: isort
    # language_version: python3.6
- repo: https://github.com/ambv/black
  rev: fc0be6eb1e2a96091e6f64009ee5e9081bf8b6c6  # frozen: 22.1.0
  hooks:
  - id: black
    exclude: regions_to_partitions.py
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
  - id: flake8
    additional_dependencies:
    - flake8-bugbear>=19.3.0
    - flake8-builtins>=1.4.1
    - flake8-commas>=2.0.0
    - flake8-comprehensions>=2.1.0
    - flake8-debugger>=3.1.0
    - flake8-pep3101>=1.2.1
    - flake8-print>=3.1.0
    # language_version: python3.6
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=4
    - --no-sort-keys
  - id: check-merge-conflict
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-mock-methods
  - id: python-no-log-warn
- repo: https://github.com/PyCQA/bandit
  rev: 1ed79063e3672a1c6d91ee27cb648e07a7465344  # frozen: 1.7.4
  hooks:
  - id: bandit
    files: "^taskcat/"
      #- repo: https://github.com/pre-commit/mirrors-mypy
      #  rev: v0.761
      #  hooks:
      #  - id: mypy
      #    files: "^taskcat/"
- repo: local
  hooks:
  - id: update-schema
    name: update-schema
    description: generate schema from dataclasses
    entry: python generate_schema.py
    language: system
    pass_filenames: false
    always_run: true
  - id: git-secrets-register-aws
    name: git-secrets-register-aws
    description: Register AWS patterns with git-secrets
    entry: git-secrets --register-aws
    language: system
    always_run: true
    pass_filenames: false
  - id: git-secrets
    name: git-secrets
    description: Run git-secrets
    entry: git-secrets --scan
    language: system
    always_run: true
  - id: update-region-mappings
    name: update-region-mappings
    description: update region-partition mappings
    entry: ./update_partition_region_map.py
    language: system
    pass_filenames: false
    always_run: true
  - id: pylint-local
    name: pylint-local
    description: Run pylint in the local virtualenv
    entry: pylint "--disable=C0209" "setup.py" "taskcat/" "bin/"
    language: system
    pass_filenames: false
    always_run: true
  - id: pytest-local
    name: pytest-local
    description: Run pytest in the local virtualenv
    entry: pytest --cov="./taskcat/"
    language: system
    pass_filenames: false
    always_run: true
